server:
   port: 8080
   servlet:
      contextpath: /res
      session:
         timeout: 60000 
   undertow:
      io-threads: 16
      worker-threads: 256
      buffer-size: 1024
      buffer-per-region: 1024
      direct-buffers: true
logging:
   level:
      root: info
      org.springframework: info
      com.yc: info
   file: D://logs/yc.log
swagger:
   enabled: false